name: Daily Log Automation
on:
  schedule:
    - cron: "30 3 * * *"  # Runs at 09:00 UTC daily
  workflow_dispatch:     # Allows manual triggers

jobs:
  run-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install papermill jupyter

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run notebook
        run: |
          papermill autolog.ipynb logs/output_$(date +\%Y-\%m-\%d).ipynb

      - name: Verify output
        run: ls logs/

      - name: Commit and push changes
        env:
            GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "redx-mistry-k"
          git config --global user.email "vkrishnaanand@gmail.com"
          git add daily_log.json
          git commit -m "Auto: Daily log update [skip ci]" || echo "No changes to commit"
          git push
